WindowManager:
	TimingWindow:
	OptionsWindow:

<TimingWindow>
	name: 'timingWindow'
	canvas.before:
		Rectangle:
			pos: self.pos
			size: self.size
			source: "images/FA20Engine4.png"
	CircularProgressBar:
		id: test
		pos: 50, 100
		thickness: 15
		cap_style: "round"
		progress_colour: "010"
		background_colour: "001"
		cap_precision: 3
		max: 150
		min: 100
		widget_size: 300
#		label: Label("AVCS_L_IN")